#!/bin/bash

just_exit()
{
    echo "Error: ($*)" 1>&2
    echo "$0 --help # for usage info"
    exit 252
}

usage()
{
    cat <<EOF
Usage:

  $0 ./{markdown-file.md} ./deeper/path/{markdown-file.md}

Copy a markdown file to another place in the repository hierarchy
while also adjusting relative links so that they still work.

The markdown experimental feature of bashctrl.sh exports a markdown
file that summarizes the steps in a bashsteps script.  When the file
is viewed from https://github.com/, each steps links to the line in
the script file where the step is defined.  The default markdown generated
by bashctrl.sh requires that the file be put at the *top* level of the git
repository, otherwise the relative links do not work.

This script adjusts the markdown file from bashctrl.sh so that the
markdown file works at deeper levels in the repository's file
hierarchy.

EOF
    exit 0
}

[[ "$*" == *--help* ]] && usage

orgpath="$1"
newpath="$2"

[ -f "$orgpath" ] || just_exit "File ($orgpath) not found"
[[ "$orgpath" == *.md ]] || just_exit "Filename ($orgpath) does not end in '.md'"
[[ "$(< "$orgpath")" == *../blob/* ]] || just_exit "File ($orgpath) was not generated by bashctrl.sh"

[ -e "$newpath" ] && just_exit "Destination file ($newpath) already exists"

orgdir="$(dirname "$(readlink -f "$orgpath")")" || exit
newdir="$(dirname "$(readlink -f "$newpath")")" || exit

deeperpart="${newdir#$orgdir}"
slashes="${deeperpart//[^\/]}"

if [ "$deeperpart" != "$newdir" ] && [ "$slashes" != "" ]; then # new dir is deeper
    frompat='/';  topat='/..'
    toadd="${slashes//$frompat/$topat}"  # Add an extra "/.." for each level deeper
    # so if slashes="//", toadd will now be "/../.."

    exec 9> "$newpath" || just_exit "Cannot open output file ($newpath)"
    if cat "$orgpath" | sed -e "s,/blob/,$toadd/blob/,g" -e "s,/tree/,$toadd/tree/,g" >&9; then
	echo "New file successfully written at $newpath"
	exit 0
    else
	rm "$newpath"
	just_exit "Error while processing with with sed"
    fi
fi

just_exit "Destination path is not deeper than original markdown file"
